version: '2'
services:
  web:
    image: junari/odoo
    ports:
      - "8069:8069"
    volumes:
      - junari-odoo-data:/opt/odoo/data
      # - junari-odoo-vscode:/opt/odoo/.vscode
      - ../.vscode:/opt/odoo/.vscode
      # - junari-odoo-custom-addons:/opt/odoo/custom_addons
      - ../custom_addons:/opt/odoo/custom_addons
      - junari-odoo-home:/home/odoo
      - ..:/opt/odoo/workspace
    env_file:
      - odoo.env
    depends_on: 
      - db
    command: bash
    tty: true

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - postgres11-data:/var/lib/postgresql/data
volumes:
  junari-odoo-data:
  # junari-odoo-vscode:
  # junari-odoo-custom-addons:
  junari-odoo-home:
  postgres11-data: